[package]
name = "webhook_builder"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros", "fs", "io-util", "process"] }
hmac = "0.12.1"
sha2 = "0.10.8"
hex = "0.4.3"
